// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.DataBase;

#nullable disable

namespace ShoppingCart.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Phones",
                            Description = "The latest iPhone with titanium design.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "IPhone 15 Pro Max",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Phones",
                            Description = "AI-powered smartphone.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Samsung Galaxy S24 Ultra",
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Category = "Laptops",
                            Description = "M3 Pro chip laptop.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "MacBook Pro 14",
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Audio",
                            Description = "Noise cancelling headphones.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Sony WH-1000XM5",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tablets",
                            Description = "M1 chip tablet.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPad Air 5",
                            Stock = 8
                        });
                });

            modelBuilder.Entity("Product.API.Entities.Product", b =>
                {
                    b.OwnsOne("Product.API.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("Currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1,
                                    Amount = 1199m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 2,
                                    Amount = 1299m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 3,
                                    Amount = 1999m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 4,
                                    Amount = 348m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = 5,
                                    Amount = 599m,
                                    Currency = "USD"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
