// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.DataBase;

#nullable disable

namespace ShoppingCart.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Product.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberofProduct")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Phones",
                            Description = "Description about products",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Product1",
                            NumberofProduct = 0,
                            Price = 15.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Phones",
                            Description = "Description about products",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Product2",
                            NumberofProduct = 0,
                            Price = 45.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phones",
                            Description = "Description about products",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Product3",
                            NumberofProduct = 0,
                            Price = 60.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phones",
                            Description = "Description about products",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Product4",
                            NumberofProduct = 0,
                            Price = 136.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Phones",
                            Description = "Description about products",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Product5",
                            NumberofProduct = 0,
                            Price = 6.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
